sudo: required
language: ruby
services:
- docker
rvm:
- 2.2.4
before_install:
- gem install bundler -v 1.10.6
script:
- bundle exec rake
- bundle exec rake build
deploy:
  provider: rubygems
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: tW8gFCUhfXV/RTxoWmNyEgHZUXgXGbLQ/8PhgoUI6kzsHfpAD3uvaFyfjOdhXTUJDjji/vw1seXLZGQCG+NWGdlsCSJP8usftQeEPsno9t5ig+WADXybiP79xYyx4wrpIr++5D9RV94zRmRfhlkh254ILKcsv1ZhTlaDBIBrFG3wF2PGRsMAVVGegHy0cfjDhwD9kuVC/EpWA/Qntbqk3+kfDrJ0N/oLVuTrr9WNXkvVEnqkp0LHEFr1lrC8uY4RR8A/lqNy2i5aAv8zDAo55d+4kK3JEEUVoUwekaqHxqONuGKUxdlSkaMT3LdKeYHelVY52NjaHWN6zngrDXcMlaDk44vFCw0hIsiLdJUJr3XXIPAyV0Lgz8cVVTUOrkjpl37zU+dylMGI5V72KgCvYCjwbuskyOwbLGiJOOF2mNp+h48M7WHSYBtK4eQv0oLncmEJvZPjBpvkeUh92P9/LtQWVtL6UielPy3N6V9tLeJ4kN1bjCHV/mD9Shfv3ksNzrKDMuZutklALu6lpRtTogFyh+MZE1vEw0+Fl57fP2UUglLMGK+C1EqrKRkQkSnblbo0xADgjsSrNhxaRIitusIVOQDu+W1s/xLPsb/8jTD0PS+wSLuWcO20zLpAqqg733ceuOY0xfihdqHyQsJdNjwC6VIxuZk4tFbGFMwT+NE=
